version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:8000"  # Host Port : Container Port
    container_name: dvdtheque_fastapi_service
    # Optional: If you need to specify the command exactly:
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000